# Generated by Django 5.1.7 on 2025-04-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lgu_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('property_number', models.CharField(max_length=50, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('Serviceable', 'Serviceable'), ('Unserviceable', 'Unserviceable')], default='Serviceable', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
