# Generated by Django 5.1.7 on 2025-04-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lgu_equipment',
            new_name='LguEquipment',
        ),
    ]
